version: '3.7'

services:
  env:
    build:
      context: docker
    restart: always
    volumes:
      - ./src:/usr/src/
    ports:
      - "8080:80"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility]
